### ISSUE TITLE
AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by rishabh004-ai** [AntreasAntoniou/HowToTrainYourMAMLPytorch#41]
Traceback (most recent call last):
  File "train_maml_system.py", line 14, in <module>
    maml_system = ExperimentBuilder(model=model, data=data, args=args, device=device)
  File "/workspace/assign_3/HowToTrainYourMAMLPytorch/experiment_builder.py", line 53, in __init__
    self.data = data(args=args, current_iter=self.state['current_iter'])
  File "/workspace/assign_3/HowToTrainYourMAMLPytorch/data.py", line 569, in __init__
    self.dataset = FewShotLearningDatasetParallel(args=args)
  File "/workspace/assign_3/HowToTrainYourMAMLPytorch/data.py", line 159, in __init__
    "train": {key: len(self.datasets['train'][key]) for key in list(self.datasets['train'].keys())},
AttributeError: 'list' object has no attribute 'keys'

**Comment by AntreasAntoniou** [comment]
I am really sorry about this. I recently applied some quick refactoring suggested by sourcery. I checked the changed but it seems this one escaped my attention. I'll resolve this shortly.

**Comment by rishabh004-ai** [comment]
Thanks a lot.

**Comment by AntreasAntoniou** [comment]
Can you give it a try now?

**Comment by AntreasAntoniou** [comment]
I am hoping that 86964701651c06e490271365fedb8789a72ef3f0 fixes it.

**Comment by rishabh004-ai** [comment]
No, I think [line 159](https://github.com/AntreasAntoniou/HowToTrainYourMAMLPytorch/blob/86964701651c06e490271365fedb8789a72ef3f0/data.py#L159) in data.py also needs to be changed.

**Comment by AntreasAntoniou** [comment]
Is this alright now? I triple checked and it runs fine on my local machine.

**Comment by AlanZhang1995** [comment]
In my understanding, you may need to modify 
https://github.com/AntreasAntoniou/HowToTrainYourMAMLPytorch/blob/86964701651c06e490271365fedb8789a72ef3f0/data.py#L186-L189
as well.

**Comment by AlanZhang1995** [comment]
I think I find the reason.
Please check whether your `mini_imagenet_full_size.json` is correct.
It would become `{}` if you did not put the dataset in correct place at the first time you run the script.
Hope this will help!

**Comment by sherry0451** [comment]
I have the same problem. Is that right to place file mini_imagenet_full_size.tar.bz2 under the folder 'datasets'? Is there other parameters needed to be modified?

**Comment by sherry0451** [comment]
I solved my problem as follows. First, automatic unzip code didn't work for my testing, so I unzip the file in terminal manually. Then I deleted the json file for miniimagenet in folder 'dataset'. Then it works.
